<?php require_once('includes/html-helper.php'); ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HTML Helper - Coding Dojo Assignment</title>
    <link rel="stylesheet" type="text/css" href="css/styles.css"/>
</head>
<body>

<div id="wrapper">

    <h1>HTML Helper - Coding Dojo Assignment</h1>


    <h3>HTML Generated by the <em>print_table</em> Method<br />of the <em>HTML_Helper</em> Class</h3>
    <?php
    // Instantiate a $generateUsersTable object
    $generateUsersTable = new HTML_Helper();

    // Call the print_table method and
    // pass in the $users array to generate HTML
    $generateUsersTable->print_table($users);
    ?>

    <h3>HTML Generated by the <em>print_select</em> Method<br />of the <em>HTML_Helper</em> Class</h3>

    <?php
    // Instantiation a $generalSelectTag object
    $generalSelectTag = new HTML_Helper();

    // Call the print_select method and
    // pass in the $states array to generate HTML
    $generalSelectTag->print_select($states);


    ?>


    

</div>

</body>
</html>